F ui 2
seeing-eye/UnforgetIt pull request #5
Opened 2017-02-19 16:11 UTC by svetlana-e-petrova

[UI-2] resolve

2017-02-19 17:12 UTC, egor-a-p requested changes

2017-02-19 17:12 UTC, egor-a-p commented on app/src/main/java/org/jasey/unforgetit/UnforgetItActivity.java
>  public class UnforgetItActivity extends AppCompatActivity {
Вынести все это добро во [фрагмент](https://developer.android.com/samples/RecyclerView/src/com.example.android.recyclerview/RecyclerViewFragment.html).

2017-02-19 17:12 UTC, egor-a-p commented on app/src/main/java/org/jasey/unforgetit/adapter/MyRecyclerViewAdapter.java
> +    private Task[] mTaskSet;
Не хочется хранить здесь таски. Таски лежат в базе. Им там хорошо. Нужно спрашивать таски у активити или фрагмента, которые знают про репозиторий. В данном случае репозиторием является этот массив. Подумай.

2017-02-19 17:12 UTC, egor-a-p commented on app/src/main/java/org/jasey/unforgetit/adapter/MyRecyclerViewAdapter.java
> +    static class ViewHolder extends RecyclerView.ViewHolder {
Странное название, странный класс. Почему он должен быть вложенным, это удобно? Почему область видимости переменных default? Это будет где-то использоваться?

2017-02-19 17:12 UTC, egor-a-p commented on app/src/main/java/org/jasey/unforgetit/adapter/MyRecyclerViewAdapter.java
> +public class MyRecyclerViewAdapter extends RecyclerView.Adapter<MyRecyclerViewAdapter.ViewHolder> {
У тебя ведь получается какой-то свой View. Почему не дать ему имя нормальное? И адаптеру, соответственно. TaskViewAdapter вроде хорошо звучит.

2017-02-19 17:13 UTC, egor-a-p commented
Вроде неплохо. Сделай изменения, и будет отлично.

2017-02-20 12:07 UTC, svetlana-e-petrova commented on app/src/main/java/org/jasey/unforgetit/adapter/MyRecyclerViewAdapter.java
> +    static class ViewHolder extends RecyclerView.ViewHolder {
Переделала. Сделала переменные приватными. Класс сделала приватным внутренним (т.к. им пользуется только адаптер), перенесла логику связывания вьюшек с тасками в этот класс.

2017-02-20 12:08 UTC, svetlana-e-petrova commented on app/src/main/java/org/jasey/unforgetit/adapter/MyRecyclerViewAdapter.java
> +    private Task[] mTaskSet;
Теперь таски получаем в адаптере статическим методом фрагмента. Так хорошо?

2017-02-20 12:09 UTC, svetlana-e-petrova commented on app/src/main/java/org/jasey/unforgetit/adapter/MyRecyclerViewAdapter.java
> +public class MyRecyclerViewAdapter extends RecyclerView.Adapter<MyRecyclerViewAdapter.ViewHolder> {
переименовала

2017-02-20 12:09 UTC, svetlana-e-petrova commented on app/src/main/java/org/jasey/unforgetit/UnforgetItActivity.java
>  public class UnforgetItActivity extends AppCompatActivity {
ок

2017-02-20 13:03 UTC, egor-a-p requested changes

2017-02-20 13:03 UTC, egor-a-p commented on app/src/main/java/org/jasey/unforgetit/UnforgetItActivity.java
> +        ft.commit();
это можно в одну строчку

2017-02-20 13:03 UTC, egor-a-p commented on app/src/main/java/org/jasey/unforgetit/UnforgetItActivity.java
> +    private TaskViewFragment taskViewFragment;
Посмотри вот это [findFragmentById(int)](https://developer.android.com/reference/android/app/FragmentManager.html#findFragmentById(int)). Что ты думаешь я к нему прицепился? Это же по сути контейнер для фрагментов.

2017-02-20 13:03 UTC, egor-a-p commented on app/src/main/java/org/jasey/unforgetit/adapter/TaskViewAdapter.java
> +    public TaskViewAdapter(Context mContext) {
Статический метод getInstance лучше конструктора.

2017-02-20 13:14 UTC, svetlana-e-petrova commented on app/src/main/java/org/jasey/unforgetit/UnforgetItActivity.java
> +    private TaskViewFragment taskViewFragment;
Я не знаю как через этот метод запустить фрагмент.  Метод фрагмента onCreateView(...) запускается только после явного вызова конструктора этого фрагмента.

2017-02-20 13:29 UTC, egor-a-p approved these changes

2017-02-20 13:29 UTC, merged